### ISSUE TITLE
Time saver Scheduler Duplication Issue

### ISSUE THREAD

**Issue by Venkat279A** [tduniec/backstage-timesaver-plugin#35]
Hi @tduniec,

We are currently facing an issue with the Backstage timesaver plugin. We are running multiple pods of Backstage, and both pods are attempting to run the scheduler, which is causing duplicate executions of our templates. Sometimes both schedulers run at the same time, leading to these duplicates. Since we can't control when one pod goes up and another goes down, we're looking for a solution.

1. Any suggestion that we can run the scheduler on a single node.
2. Is there a way to customize the schedule time for configuration file?

Any suggestions on how to resolve this would be greatly appreciated!

**Comment by tduniec** [comment]
hello @Venkat279A 

I think if you can add some randomness into the handler of timesaving collector it can be helpful here. if the container is starting in the same time there can be conflict now, even if the scheduler is the built-in backstage mechanism and it runs alongside with single backstage table it may still have a conflict. i think adding randomness in seconds to ts handler will improve the performance here. 

I will take a look into it in couple of days

**Comment by Venkat279A** [comment]
Hi @tduniec , Thank you for your assistance.

1. Could you advise on where we might incorporate randomness within the timesaver handler?
2. Is there a recommended approach to ensure that when timesaver is run on separate pods, the same task is not executed twice, avoiding conflicts between pods?
3. Lastly, is it possible to configure the config.yaml file to handle the randomness value externally, allowing for adjustments without modifying the codebase?

Thank you for your insights.

**Comment by Venkat279A** [comment]
Hi @tduniec,

Just checking in to see if you had a chance to look into the suggestions we discussed above. Any insights on implementing those would be greatly appreciated!

Thanks again for your support!

**Comment by tduniec** [comment]
Hello @Venkat279A 

Modified a little according to documentation 

https://backstage.io/docs/reference/backend-plugin-api.schedulerservicetaskscheduledefinition.scope

previously was passed as `undefined`, so fixed to add this value

Please let me know if this helps fixing the issue because it should by its definition

**Comment by Venkat279A** [comment]
Hi @tduniec,

Thank you for the suggestion and the reference to the documentation.

I tried adding the scope value as per the documentation, but unfortunately, the issue persists.

Let me know if you have any further suggestions

**Comment by tduniec** [comment]
> Hi @tduniec,
> 
> Thank you for the suggestion and the reference to the documentation.
> 
> I tried adding the scope value as per the documentation, but unfortunately, the issue persists.
> 
> Let me know if you have any further suggestions

Hello @Venkat279A 

Have you tried it with updated package ?

Please check the latest timesaver plugin **backend version (4.1.0)**, this one should fix the problem. Configuration of the scheduler is not required.

**Comment by Venkat279A** [comment]
Hi @tduniec,

I have tried using the latest version of the TimeSaver plugin backend (4.1.0), but unfortunately, it still did not resolve the issue. The problem persists even with the updated package.
